DELETE FROM MOVIE_ACTOR;
DELETE FROM MOVIE_GENRE;
DELETE FROM MOVIE_DIRECTOR;
DELETE FROM POSTER;
DELETE FROM REVIEW;
DELETE FROM ARTIST;
DELETE FROM GENRE;
DELETE FROM MOVIE;
DELETE FROM USERS;

DELETE FROM INFOS;
DELETE FROM ERREURS;