INSERT INTO CERTIFICATION(ID, NAME, DESCRIPTION) VALUES(1, 'G', '');
INSERT INTO CERTIFICATION(ID, NAME, DESCRIPTION) VALUES(2, 'PG', '');
INSERT INTO CERTIFICATION(ID, NAME, DESCRIPTION) VALUES(3, 'PG-13', '');
INSERT INTO CERTIFICATION(ID, NAME, DESCRIPTION) VALUES(4, 'R', '');
INSERT INTO CERTIFICATION(ID, NAME, DESCRIPTION) VALUES(5, 'NC-17', '');

INSERT INTO STATUS(ID, NAME) VALUES(1, 'Post Production');
INSERT INTO STATUS(ID, NAME) VALUES(2, 'Rumored');
INSERT INTO STATUS(ID, NAME) VALUES(3, 'Released');
INSERT INTO STATUS(ID, NAME) VALUES(4, 'In Production');
INSERT INTO STATUS(ID, NAME) VALUES(5, 'Planned');
INSERT INTO STATUS(ID, NAME) VALUES(6, 'Canceled');